version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro 
      - ./react-app/build:/usr/share/nginx/html:ro 
    depends_on:
      - php-backend
    networks:
      - app-network

  php-backend:
    build:
      context: ./php-backend
      dockerfile: Dockerfile.php
    container_name: php-backend
    ports:
      - "8080:80"
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poke_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
