version: "3"

services:
  php-backend:
    build:
      context: ./php-backend
      dockerfile: Dockerfile.php
    container_name: php-backend
    volumes:
      - ./php-backend:/var/www/html
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pokemon_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
