CREATE DATABASE IF NOT EXISTS pokemon_db;
CREATE USER IF NOT EXISTS 'user'@'%' IDENTIFIED BY 'pass';
GRANT ALL PRIVILEGES ON pokemon_db.* TO 'user'@'%';
FLUSH PRIVILEGES;

USE pokemon_db;

CREATE TABLE IF NOT EXISTS pokemon_cache (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    data LONGTEXT NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
